config/routes.rb
Rails.application.routes.draw do

  resources :games do
    resources :achievements
  end

  namespace :api do
    namespace :v1 do
      resources :game do
        get :register_player
      end
    end
  end

  resources :studios

  devise_for :players
  devise_for :developers

  resources :stats, only: [:show]

  root to: 'home#index'

  get 'developers', to: 'home#developers'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :studio
  has_and_belongs_to_many :players
  after_validation :build_game_id
  after_create :add_stats

  # We don't want this to change as it is the way games are associated with users.
  # We'll use this instead of the primary key for security reasons.
  def build_game_id
    if !game_id
      self.game_id = Digest::SHA1.hexdigest("#{studio_id}_#{id}_#{name}")
    end
  end

  def add_stats
    if !self.game_stats
      stats = GameStat.new
      stats.save

      self.game_stats = stats.id
      self.save!
    end
  end
end

app/controllers/api/v1/game_controller.rb
module Api
  module V1
    class GameController < ApiController
      def index
        render json: {}
      end

      def register_player
        # Using where clause instead of select for case-independent search
        if params[:handle]
          @player = Player.where('lower(handle) = ?', params[:handle].downcase).first
        elsif params[:email]
          @player = Player.where('lower(email) = ?', params[:email].downcase).first
        end

        if @player.nil?
          head :nor_found
        else
          @game = Game.find_by(game_id: params[:game_id])

          if @player.games.detect { |g| g.game_id == @game.game_id }
            head :conflict
          else
            @player.games << @game
            render json: {status: 200,
                          message: 'Registered Player'}
          end
        end
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_developer!

  # GET /games
  # GET /games.json
  def index
    debugger
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by(game_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :cover_image_loc, :studio_id, :game_id, :auth_token)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.slim
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  div.form-group.field
    h1.push-top= f.label :name, 'Game Name'
    = f.text_field :name, class: 'form-control'
  div.form-group.field
    = f.label :description
    = f.text_field :description, class: 'form-control'
  div.form-group.field
    = f.label :cover_image_loc
    = f.text_field :cover_image_loc, class: 'form-control'
  div.form-group.field
    = f.label :studio
    = f.text_field :studio, class: 'form-control'
  div.form-group.field
    = f.label :auth_token
    = f.text_field :auth_token, class: 'form-control'
  br
  div.row
    div.col-xs-6
      .actions = f.submit 'Save', class: 'btn btn-primary col-xs-3'
    div.col-xs-6.pull-right
      = link_to 'Back', studios_path, class: 'btn btn-primary pull-right col-xs-3'
  br

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'|
= link_to 'Back', games_path

app/views/games/index.html.slim
h1 Listing games

table
  thead
    tr
      th Name
      th Description
      th Cover image loc
      th Studio
      th Game
      th Auth token
      th
      th
      th

  tbody
    - @games.each do |game|
      tr
        td = game.name
        td = game.description
        td = game.cover_image_loc
        td = game.studio
        td = game.game_id
        td = game.auth_token
        td = link_to 'Show', game
        td = link_to 'Edit', edit_game_path(game)
        td = link_to 'Destroy', game, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Game', new_game_path

app/views/games/new.html.slim
div.col-xs-3
div.col-xs-6
  == render 'form'

app/views/games/show.html.slim
p#notice = notice

p
  strong Name:
  = @game.name
p
  strong Description:
  = @game.description
p
  strong Cover image loc:
  = @game.cover_image_loc
p
  strong Studio:
  = @game.studio
p
  strong Game:
  = @game.game_id
p
  strong Auth token:
  = @game.auth_token

= link_to 'Edit', edit_game_path(@game)
'|
= link_to 'Back', games_path