config/routes.rb
Rails.application.routes.draw do

  resources :games do
    resources :achievements
  end

  namespace :api do
    namespace :v1 do
      resources :game do
        get :register_player
      end
    end
  end

  resources :studios

  devise_for :players
  devise_for :developers

  resources :stats, only: [:show]

  root to: 'home#index'

  get 'developers', to: 'home#developers'
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :game

  has_and_belongs_to_many :players
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :set_game
  before_action :set_achievement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_developer!

  # GET /achievements
  # GET /achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /achievements/1
  # GET /achievements/1.json
  def show
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /achievements/1/edit
  def edit
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to @achievement, notice: 'Achievement was successfully created.' }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1
  # PATCH/PUT /achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to @achievement, notice: 'Achievement was successfully updated.' }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url, notice: 'Achievement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by(game_id: params[:game_id])
    end

    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def achievement_params
      params.require(:achievement).permit(:name, :description, :icon_loc, :point_value, :game_id)
    end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/views/achievements/_form.html.slim
= form_for @achievement do |f|
  - if @achievement.errors.any?
    #error_explanation
      h2 = "#{pluralize(@achievement.errors.count, "error")} prohibited this achievement from being saved:"
      ul
        - @achievement.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :icon_loc
    = f.text_field :icon_loc
  .field
    = f.label :point_value
    = f.number_field :point_value
  .field
    = f.label :game
    = f.text_field :game
  .actions = f.submit 'Save'

app/views/achievements/edit.html.slim
h1 Editing achievement

== render 'form'

= link_to 'Show', @achievement
'|
= link_to 'Back', game_achievements_path

app/views/achievements/index.html.slim
h1 <strong>#{@game.name}</strong> Achievements

table
  thead
    tr
      th Name
      th Description
      th Icon loc
      th Point value
      th Game
      th
      th
      th

  tbody
    - @achievements.each do |achievement|
      tr
        td = achievement.name
        td = achievement.description
        td = achievement.icon_loc
        td = achievement.point_value
        td = achievement.game
        td = link_to 'Show', game_achievement
        td = link_to 'Edit', edit_game_achievement_path(achievement)
        td = link_to 'Destroy', game_achievement, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Achievement', new_game_achievement_path

app/views/achievements/new.html.slim
h1 New achievement

== render 'form'

= link_to 'Back', achievements_path

app/views/achievements/show.html.slim
p#notice = notice

p
  strong Name:
  = @achievement.name
p
  strong Description:
  = @achievement.description
p
  strong Icon loc:
  = @achievement.icon_loc
p
  strong Point value:
  = @achievement.point_value
p
  strong Game:
  = @achievement.game

= link_to 'Edit', edit_achievement_path(@achievement)
'|
= link_to 'Back', achievements_path