config/routes.rb
Rails.application.routes.draw do

  resources :games do
    resources :achievements
  end

  namespace :api do
    namespace :v1 do
      resources :game do
        get :register_player
      end
    end
  end

  resources :studios

  devise_for :players
  devise_for :developers

  resources :stats, only: [:show]

  root to: 'home#index'

  get 'developers', to: 'home#developers'
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  # The role enumerates the role column of the Studio/Developer Join Table
  # it dictates what permissions a given user has with the studio.
  enum role: [:admin, :developer]

  has_and_belongs_to_many :developers
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_developer!

  # GET /studios
  # GET /studios.json
  def index
    @studios = Studio.all
  end

  # GET /studios/1
  # GET /studios/1.json
  def show
  end

  # GET /studios/new
  def new
    @studio = Studio.new
  end

  # GET /studios/1/edit
  def edit
  end

  # POST /studios
  # POST /studios.json
  def create
    @studio = Studio.new(studio_params)

    respond_to do |format|
      if @studio.save
        @studio.developers << current_developer
        format.html { redirect_to @studio, notice: 'Studio was successfully created.' }
        format.json { render :show, status: :created, location: @studio }
      else
        format.html { render :new }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studios/1
  # PATCH/PUT /studios/1.json
  def update
    respond_to do |format|
      if @studio.update(studio_params)
        format.html { redirect_to @studio, notice: 'Studio was successfully updated.' }
        format.json { render :show, status: :ok, location: @studio }
      else
        format.html { render :edit }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1
  # DELETE /studios/1.json
  def destroy
    @studio.destroy
    respond_to do |format|
      format.html { redirect_to studios_url, notice: 'Studio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studio
      @studio = Studio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studio_params
      params.require(:studio).permit(:name, :description, :poc_name, :poc_email, :poc_phone, :address, :secondary_address, :state_province, :country, :zip_postal)
    end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_form.html.slim
= form_for @studio do |f|
  - if @studio.errors.any?
    #error_explanation
      h2 = "#{pluralize(@studio.errors.count, "error")} prohibited this studio from being saved:"
      ul
        - @studio.errors.full_messages.each do |message|
          li = message

  h1.push-top Studio
  div.form-group.field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  h4 Point of Contact
  div.form-group.field
    = f.label :poc_name, 'Name'
    = f.text_field :poc_name, class: 'form-control'
  div.form-group.field
    = f.label :poc_email, 'Email'
    = f.text_field :poc_email, class: 'form-control'
  div.form-group.field
    = f.label :poc_phone, 'Phone Number'
    = f.text_field :poc_phone, class: 'form-control'
  div.form-group.field
    = f.label :address, 'Address'
    = f.text_field :address, class: 'form-control'
  div.form-group.field
    = f.label :secondary_address, 'Secondary Address'
    = f.text_field :secondary_address, class: 'form-control'
  div.form-group.field
    = f.label :state_province, "State/Province"
    = f.text_field :state_province, class: 'form-control'
  div.form-group.field
    = f.label :country
    = f.text_field :country, class: 'form-control'
  div.form-group.field
    = f.label :zip_postal, "Zip/Postal Code"
    = f.text_field :zip_postal, class: 'form-control'
  br
  div.row
    div.col-xs-6
      .actions = f.submit 'Save', class: 'btn btn-primary col-xs-3'
    div.col-xs-6.pull-right
      = link_to 'Back', studios_path, class: 'btn btn-pull-right col-xs-3'
  br

app/views/studios/edit.html.slim
h1 Editing studio

== render 'form'

= link_to 'Show', @studio
'|
= link_to 'Back', studios_path

app/views/studios/index.html.slim
h1 Listing studios

table
  thead
    tr
      th Name
      th Description
      th Poc name
      th Poc email
      th Poc phone
      th Address
      th Secondary address
      th State province
      th Country
      th Zip postal
      th
      th
      th

  tbody
    - @studios.each do |studio|
      tr
        td = studio.name
        td = studio.description
        td = studio.poc_name
        td = studio.poc_email
        td = studio.poc_phone
        td = studio.address
        td = studio.secondary_address
        td = studio.state_province
        td = studio.country
        td = studio.zip_postal
        td = link_to 'Show', studio
        td = link_to 'Edit', edit_studio_path(studio)
        td = link_to 'Destroy', studio, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Studio', new_studio_path

app/views/studios/new.html.slim
div.col-xs-3
div.col-xs-6
  == render 'form'

app/views/studios/show.html.slim
p#notice = notice

p
  strong Name:
  = @studio.name
p
  strong Description:
  = @studio.description
p
  strong Poc name:
  = @studio.poc_name
p
  strong Poc email:
  = @studio.poc_email
p
  strong Poc phone:
  = @studio.poc_phone
p
  strong Address:
  = @studio.address
p
  strong Secondary address:
  = @studio.secondary_address
p
  strong State province:
  = @studio.state_province
p
  strong Country:
  = @studio.country
p
  strong Zip postal:
  = @studio.zip_postal

= link_to 'Edit', edit_studio_path(@studio)
'|
= link_to 'Back', studios_path